# Generated by Django 4.2.13 on 2026-06-02 12:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='tokens_used',
            new_name='tokens_estimate',
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='generation_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10),
        ),
        migrations.CreateModel(
            name='RetrievedChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=512)),
                ('texte', models.TextField()),
                ('source_file', models.CharField(max_length=1024)),
                ('score', models.FloatField()),
                ('raw_meta', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved_chunks', to='chat.message')),
            ],
            options={
                'verbose_name': 'Retrieved Chunk',
                'verbose_name_plural': 'Retrieved Chunks',
                'db_table': 'retrieved_chunks',
            },
        ),
    ]
