# Generated by Django 4.2.13 on 2026-05-04 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Star rating 1–5', null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful')], max_length=15, null=True)),
                ('issue_type', models.CharField(blank=True, choices=[('incorrect', 'Incorrect Information'), ('incomplete', 'Incomplete Answer'), ('too_long', 'Too Long'), ('too_short', 'Too Short'), ('off_topic', 'Off Topic'), ('harmful', 'Harmful Content'), ('other', 'Other')], max_length=20, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.conversation')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback',
                'ordering': ['-timestamp'],
            },
        ),
    ]
